version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - mynetwork

  publisher1:
    build:
      context: .
      dockerfile: RabbitPublisherSample/Dockerfile
    image: publisher
    depends_on:
      - rabbitmq
    networks:
      - mynetwork

  consumer1:
    build:
      context: .
      dockerfile: RabbitConsumerSample/Dockerfile
    image: consumer
    environment:
      - ConsumerName=consumer-1
    depends_on:
      - rabbitmq
    networks:
      - mynetwork

  consumer2:
    image: consumer
    environment:
      - ConsumerName=consumer-2
    depends_on:
      - rabbitmq
    networks:
      - mynetwork

  consumer3:
    image: consumer
    environment:
      - ConsumerName=consumer-3
    depends_on:
      - rabbitmq
    networks:
      - mynetwork

networks:
  mynetwork:
